<%
out.println("<!DOCTYPE html>");
out.println("<!--");
out.println("	Active by TEMPLATE STOCK");
out.println("	templatestock.co @templatestock");
out.println("	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)");
out.println("-->");
out.println("");
out.println("<html lang=\"en-US\">");
out.println("<head>");
out.println("	<meta charset=\"UTF-8\">");
out.println("	<title>Active - HTML5 Responsive Template | Template Stock</title>");
out.println("	");
out.println("	<!-- Main CSS file -->");
out.println("	<link rel=\"stylesheet\" href=\"css/style.css\" />");
out.println("	");
out.println("	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->");
out.println("	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->");
out.println("	<!--[if lt IE 9]>");
out.println("	  <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>");
out.println("	  <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>");
out.println("	<![endif]-->");
out.println("	");
out.println("</head>");
out.println("<body>");
out.println("");
out.println("	<!-- PRELOADER -->");
out.println("	<div id=\"st-preloader\">");
out.println("		<div id=\"pre-status\">");
out.println("			<div class=\"preload-placeholder\"></div>");
out.println("		</div>");
out.println("	</div>");
out.println("	<!-- /PRELOADER -->");
out.println("");
out.println("	<!-- HEADER -->");
out.println("	<header class=\"st-header st-fullHeight\">");
out.println("		<div class=\"header-overlay\"></div><!-- /HEADER OVERLY -->");
out.println("		<div class=\"container\">");
out.println("			<div class=\"row\">");
out.println("				<div class=\"col-md-12 text-center st-header-content\">");
out.println("					<div class=\"logo\"><a href=\"\"><img src=\"images/logo.png\" alt=\"\"></a></div>");
out.println("					<div class=\"st-header-title\">");
out.println("						<h2>Welcome <span>Azure DevOps Demo </span></h2>");
out.println("						<p> a demo webapplication <br /> created during devops training for Venky-Team</p>");
out.println("					</div>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("		<a href=\"#service\" class=\"mouse-icon hidden-xs\">");
out.println("			<div class=\"wheel\"></div>");
out.println("		</a>");
out.println("	</header>");
out.println("	<!-- /HEADER -->");
out.println("");
out.println("	<!-- SERVICE ICONS -->");
out.println("	<section id=\"service\" class=\"service-icons\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"row\">");
out.println("				<div class=\"col-sm-4 st-service-box\">");
out.println("					<span><i class=\"fa fa-cogs\"></i></span>");
out.println("					<h3 class=\"text-uppercase\">Development</h3>");
out.println("					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi nemo, ea omnis architecto cumque? Necessitatibus.</p>");
out.println("					<a href=\"#\">More info</a>");
out.println("				</div>");
out.println("");
out.println("				<div class=\"col-sm-4 st-service-box\">");
out.println("					<span><i class=\"fa fa-life-ring\"></i></span>");
out.println("					<h3 class=\"text-uppercase\">Friendly Support</h3>");
out.println("					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi nemo, ea omnis architecto cumque? Necessitatibus.</p>");
out.println("					<a href=\"#\">More info</a>");
out.println("				</div>");
out.println("");
out.println("				<div class=\"col-sm-4 st-service-box\">");
out.println("					<span><i class=\"fa fa-weixin\"></i></span>");
out.println("					<h3 class=\"text-uppercase\">Live Support</h3>");
out.println("					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi nemo, ea omnis architecto cumque? Necessitatibus.</p>");
out.println("					<a href=\"#\">More info</a>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</section>");
out.println("	<!-- /SERVICE ICONS -->");
out.println("");
out.println("	<!-- SUBSCRIBE -->");
out.println("	<section class=\"subscribe\">");
out.println("		<div class=\"color-overlay\"></div><!-- /COLOR OVERLY -->");
out.println("		<div class=\"container\">");
out.println("			<div class=\"row\">");
out.println("				<div class=\"col-md-6 col-md-offset-3 subscribe-form\">");
out.println("					<div class=\"st-subscribe-title text-center\">");
out.println("						<h3>Subscribe to our newsletter</h3>");
out.println("						<p>No spam promise - only our latest news and freebies!</p>");
out.println("					</div>");
out.println("					<!-- FORM -->");
out.println("					<form id=\"subscribe\">");
out.println("						<input type=\"email\" value=\"\" name=\"subscribe-email\" id=\"st-email\" placeholder=\"Enter your e-mail\">");
out.println("						<input type=\"submit\" name=\"subscribe-submit\" value=\"Subscribe\">");
out.println("						<label for=\"st-email\" class=\"st-subscribe-message\"></label>");
out.println("					</form>");
out.println("					<!-- /FORM -->");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</section>");
out.println("	<!-- /SUBSCRIBE -->");
out.println("");
out.println("	<!-- CONTACT -->");
out.println("	<section class=\"contact\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"row\">");
out.println("				<div class=\"col-sm-6 contact-info\">");
out.println("					<h2 class=\"contact-title text-uppercase\">Contact us</h2>");
out.println("					<p class=\"contact-content\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae voluptatum dolorum, possimus tenetur pariatur officia, quo commodi autem doloribus vero rerum aspernatur quidem temporibus.</p>");
out.println("					<p class=\"st-address\"><i class=\"fa fa-map-marker\"></i> <strong>E71 8th Ave, New York NY 21001, US</strong></p>");
out.println("					<p class=\"st-phone\"><i class=\"fa fa-mobile\"></i> <strong>123-456-789</strong></p>");
out.println("					<p class=\"st-email\"><i class=\"fa fa-envelope-o\"></i> <strong>email@yourdomain.com</strong></p>");
out.println("					<p class=\"st-website\"><i class=\"fa fa-globe\"></i> <strong>www.yourdomain.com</strong></p>");
out.println("				</div>");
out.println("				<div class=\"col-sm-6 contact-form\">");
out.println("					<div class=\"st-contact-message\">");
out.println("");
out.println("					</div>");
out.println("					<form id=\"\" name=\"contact-form\" method=\"post\" action=\"\" >");
out.println("						<input type=\"text\" name=\"name\" required=\"required\" id=\"contact-name\" placeholder=\"Your Name\">");
out.println("						<input type=\"email\" name=\"email\" required=\"required\" id=\"contact-email\" placeholder=\"Your Email\">");
out.println("						<textarea placeholder=\"Massage\" name=\"message\" required=\"required\" id=\"contact-message\" cols=\"70\" rows=\"6\"></textarea>");
out.println("						<input type=\"submit\" value=\"Send message\" name=\"contact-submit\">");
out.println("					</form>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</section>");
out.println("	<!-- /CONTACT -->");
out.println("");
out.println("	<!-- FOOTER -->");
out.println("	<footer class=\"footer\">");
out.println("		<div class=\"container\">");
out.println("			<div class=\"row\">");
out.println("				<!-- SOCIAL ICONS -->");
out.println("				<div class=\"col-sm-6 col-sm-push-6 social-icons\">");
out.println("					<a href=\"\"><i class=\"fa fa-facebook\"></i></a>");
out.println("					<a href=\"\"><i class=\"fa fa-twitter\"></i></a>");
out.println("					<a href=\"\"><i class=\"fa fa-google-plus\"></i></a>");
out.println("					<a href=\"\"><i class=\"fa fa-pinterest-p\"></i></a>");
out.println("				</div>");
out.println("				<!-- /SOCIAL ICONS -->");
out.println("				<div class=\"col-sm-6 col-sm-pull-6 copyright\">");
out.println("					<p>&copy; 2016 <a href=\"http://templatestock.co\">Template Stock</a>. All Rights Reserved.</p>");
out.println("				</div>");
out.println("			</div>");
out.println("		</div>");
out.println("	</footer>");
out.println("	<!-- /FOOTER -->");
out.println("	");
out.println("	<!-- JS -->");
out.println("	<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script><!-- jQuery -->");
out.println("	<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script><!-- Bootstrap -->");
out.println("	<script type=\"text/javascript\" src=\"js/jquery.parallax.js\"></script><!-- Parallax -->");
out.println("	<script type=\"text/javascript\" src=\"js/smoothscroll.js\"></script><!-- Smooth Scroll -->");
out.println("	<script type=\"text/javascript\" src=\"js/scripts.js\"></script><!-- Scripts -->");
out.println("");
out.println("</body>");
out.println("</html>");
%>
